const firebaseConfig={apiKey:"AIzaSyDprZtAn7CdeRoeoyO7uel59936xxWIo1g",authDomain:"ai-signal-portal.firebaseapp.com",projectId:"ai-signal-portal",storageBucket:"ai-signal-portal.firebasestorage.app",messagingSenderId:"708453018931",appId:"1:708453018931:web:201c1649e4da9d62e56246",measurementId:"G-1BBZXCCNL2"};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth();
const db=firebase.firestore();
const googleProvider=new firebase.auth.GoogleAuthProvider();
let currentUser=null;
let currentSignalId=null;
let prevPage='home';
let currentPortfolioFilter='all';
let portfolios=[];
let currentTheme=localStorage.getItem('theme')||'theme-wuxing';
let currentLang=localStorage.getItem('lang')||'en';
function setTheme(t){currentTheme=t;localStorage.setItem('theme',t);document.documentElement.className=t;}
function setLang(l){currentLang=l;localStorage.setItem('lang',l);}
function navigate(page){if(page==='mysignals'&&!currentUser)return;document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));document.getElementById('page-'+page).classList.add('active');const nav=document.getElementById('nav-'+page);if(nav)nav.classList.add('active');prevPage=page;if(page==='home')loadHomeSignals();if(page==='mysignals')loadMySignals();}
function goBack(){navigate(prevPage==='detail'?'home':prevPage);}
function openSignalDetail(id){currentSignalId=id;prevPage=document.querySelector('.nav-item.active')?.id?.replace('nav-','')||'home';document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-detail').classList.add('active');loadSignalDetail(id);}
function signInWithGoogle(){auth.signInWithPopup(googleProvider).catch(e=>alert(e.message));}
function signOut(){auth.signOut();}
auth.onAuthStateChanged(user=>{currentUser=user;if(user){document.getElementById('loginBtn').style.display='none';document.getElementById('userInfo').style.display='flex';document.getElementById('userAvatar').src=user.photoURL||'';document.getElementById('userName').textContent=user.displayName||user.email;document.getElementById('nav-mysignals').classList.remove('locked');db.collection('users').doc(user.uid).set({uid:user.uid,displayName:user.displayName,email:user.email,photoURL:user.photoURL,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});loadPortfolios();}else{document.getElementById('loginBtn').style.display='inline-block';document.getElementById('userInfo').style.display='none';document.getElementById('nav-mysignals').classList.add('locked');portfolios=[];}loadHomeSignals();});
function loadPortfolios(){if(!currentUser)return;db.collection('portfolios').where('ownerUid','==',currentUser.uid).orderBy('createdAt','asc').onSnapshot(snap=>{portfolios=[{id:'all',name:'All'}];snap.forEach(doc=>portfolios.push({id:doc.id,name:doc.data().name}));renderPortfolioBar();renderPortfolioSelect();});}
function renderPortfolioBar(){const bar=document.getElementById('portfolioBar');if(!bar)return;bar.innerHTML='';portfolios.forEach(p=>{const el=document.createElement('div');el.className='ptab'+(p.id===currentPortfolioFilter?' active':'');el.textContent=p.name;el.onclick=()=>switchPortfolio(p.id);bar.appendChild(el);});const btn=document.createElement('button');btn.className='btn-add-ptab';btn.textContent='+ Portfolio';btn.onclick=openAddPortfolioModal;bar.appendChild(btn);}
function renderPortfolioSelect(){const sel=document.getElementById('signalPortfolio');if(!sel)return;sel.innerHTML='<option value="">— None —</option>';portfolios.filter(p=>p.id!=='all').forEach(p=>{sel.innerHTML+=`<option value="${p.id}">${p.name}</option>`;});}
function switchPortfolio(pid){currentPortfolioFilter=pid;renderPortfolioBar();loadMySignals();}
function openAddPortfolioModal(){document.getElementById('addPortfolioModal').style.display='flex';}
function closeAddPortfolioModal(){document.getElementById('addPortfolioModal').style.display='none';document.getElementById('portfolioName').value='';}
function submitAddPortfolio(){if(!currentUser)return;const name=document.getElementById('portfolioName').value.trim();if(!name)return;db.collection('portfolios').add({name,ownerUid:currentUser.uid,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(()=>closeAddPortfolioModal());}
let homeUnsub=null;
function loadHomeSignals(){const grid=document.getElementById('homeSignalGrid');const plat=document.getElementById('filterPlatform')?.value||'all';const sort=document.getElementById('filterSort')?.value||'newest';if(homeUnsub)homeUnsub();let q=db.collection('signals').where('visibility','==','public');if(plat!=='all')q=q.where('platform','==',plat);q=q.orderBy(sort==='likes'?'likesCount':'createdAt','desc');homeUnsub=q.onSnapshot(snap=>{if(snap.empty){grid.innerHTML='<div class="empty-msg">No public signals found.</div>';return;}grid.innerHTML='';snap.forEach(doc=>grid.appendChild(buildCard(doc,false)));});}
let myUnsub=null;
function loadMySignals(){if(!currentUser)return;const grid=document.getElementById('mySignalGrid');if(myUnsub)myUnsub();db.collection('signals').where('ownerUid','==',currentUser.uid).orderBy('createdAt','desc').onSnapshot(snap=>{let docs=snap.docs;if(currentPortfolioFilter!=='all')docs=docs.filter(d=>d.data().portfolioId===currentPortfolioFilter);if(docs.length===0){grid.innerHTML='<div class="empty-msg">No signals yet.</div>';return;}grid.innerHTML='';docs.forEach(doc=>grid.appendChild(buildCard(doc,true)));});}
function buildCard(doc,isOwner){const s=doc.data();const id=doc.id;const visCls=s.visibility==='public'?'badge-public':'badge-private';const visLbl=s.visibility==='public'?'Public':'Private';const card=document.createElement('div');card.className='signal-card';card.innerHTML=`<div class="card-top"><div class="card-name">${s.name||'—'}</div><span class="badge ${visCls}">${visLbl}</span>${isOwner?`<button class="btn-delete" onclick="event.stopPropagation();deleteSignal('${id}')">🗑</button>`:''}</div><div class="card-meta"><span>📊 ${s.platform?s.platform.toUpperCase():'—'}</span><span>🏦 ${s.broker||'—'}</span><span>🤖 ${s.eaName||'—'}</span></div><div class="card-footer"><button class="btn-like" onclick="event.stopPropagation();likeSignal('${id}')">👍 <span id="lk-${id}">${s.likesCount||0}</span></button><span>💬 ${s.commentsCount||0}</span><span>@${s.ownerName||'unknown'}</span></div>`;card.onclick=()=>openSignalDetail(id);return card;}
function openAddSignalModal(){if(!currentUser)return;renderPortfolioSelect();document.getElementById('addSignalModal').style.display='flex';}
function closeAddSignalModal(){document.getElementById('addSignalModal').style.display='none';['signalName','signalBroker','signalEaName'].forEach(i=>document.getElementById(i).value='');}
function submitAddSignal(){if(!currentUser)return;const name=document.getElementById('signalName').value.trim();if(!name)return;db.collection('signals').add({name,broker:document.getElementById('signalBroker').value.trim(),platform:document.getElementById('signalPlatform').value,eaName:document.getElementById('signalEaName').value.trim(),portfolioId:document.getElementById('signalPortfolio').value,visibility:document.getElementById('signalVisibility').value,ownerUid:currentUser.uid,ownerName:currentUser.displayName||currentUser.email,likesCount:0,commentsCount:0,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(()=>closeAddSignalModal()).catch(e=>console.error(e));}
function deleteSignal(id){if(!currentUser)return;if(!confirm('Confirm delete this signal?'))return;db.collection('signals').doc(id).delete().catch(e=>console.error(e));}
function likeSignal(signalId){if(!currentUser){alert('Please login first.');return;}const likeRef=db.collection('signalLikes').doc(`${signalId}_${currentUser.uid}`);const sigRef=db.collection('signals').doc(signalId);likeRef.get().then(doc=>{if(doc.exists){likeRef.delete();sigRef.update({likesCount:firebase.firestore.FieldValue.increment(-1)});}else{likeRef.set({signalId,userId:currentUser.uid,createdAt:firebase.firestore.FieldValue.serverTimestamp()});sigRef.update({likesCount:firebase.firestore.FieldValue.increment(1)});}});}
function loadSignalDetail(id){db.collection('signals').doc(id).get().then(doc=>{if(!doc.exists)return;const s=doc.data();const visCls=s.visibility==='public'?'badge-public':'badge-private';document.getElementById('detailTitle').innerHTML=`${s.name||'—'} <span class="badge ${visCls}">${s.visibility}</span>`;document.getElementById('detailMeta').innerHTML=`<span>📊 ${s.platform?s.platform.toUpperCase():'—'}</span><span>🏦 ${s.broker||'—'}</span><span>🤖 ${s.eaName||'—'}</span><span>👤 @${s.ownerName||'unknown'}</span><span>👍 ${s.likesCount||0}</span>`;});switchDTab('account');loadOpenOrders(id);}
function switchDTab(tab){document.querySelectorAll('.dtab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.dpanel').forEach(p=>p.classList.remove('active'));document.getElementById('dtab-'+tab).classList.add('active');document.getElementById('dpanel-'+tab).classList.add('active');if(tab==='history')loadOrderHistory(currentSignalId);if(tab==='stats')loadStats(currentSignalId);}
function loadOpenOrders(signalId){db.collection('signals').doc(signalId).collection('openOrders').orderBy('openTime','desc').onSnapshot(snap=>{const tbody=document.getElementById('openOrdersBody');if(snap.empty){tbody.innerHTML='<tr><td colspan="8" style="text-align:center;color:var(--sub);padding:30px">No open orders.</td></tr>';return;}tbody.innerHTML='';snap.forEach(doc=>{const o=doc.data();const profitCls=o.profit>=0?'pos':'neg';tbody.innerHTML+=`<tr><td>${o.ticket||'—'}</td><td>${o.symbol||'—'}</td><td>${o.type||'—'}</td><td>${o.lots||'—'}</td><td>${o.openPrice||'—'}</td><td>${o.currentPrice||'—'}</td><td class="${profitCls}">${o.profit||0}</td><td>${o.openTime||'—'}</td></tr>`;});});}
function loadOrderHistory(signalId){db.collection('signals').doc(signalId).collection('orderHistory').orderBy('closeTime','desc').onSnapshot(snap=>{const tbody=document.getElementById('historyBody');if(snap.empty){tbody.innerHTML='<tr><td colspan="9" style="text-align:center;color:var(--sub);padding:30px">No history.</td></tr>';return;}tbody.innerHTML='';snap.forEach(doc=>{const o=doc.data();const profitCls=o.profit>=0?'pos':'neg';tbody.innerHTML+=`<tr><td>${o.ticket||'—'}</td><td>${o.symbol||'—'}</td><td>${o.type||'—'}</td><td>${o.lots||'—'}</td><td>${o.openPrice||'—'}</td><td>${o.closePrice||'—'}</td><td class="${profitCls}">${o.profit||0}</td><td>${o.openTime||'—'}</td><td>${o.closeTime||'—'}</td></tr>`;});calcStats(snap.docs.map(d=>d.data()));});}
function loadStats(signalId){db.collection('signals').doc(signalId).collection('orderHistory').get().then(snap=>{calcStats(snap.docs.map(d=>d.data()));});}
function calcStats(orders){if(!orders.length)return;const total=orders.length;const wins=orders.filter(o=>o.profit>0).length;const winRate=((wins/total)*100).toFixed(1)+'%';const totalProfit=orders.reduce((s,o)=>s+(o.profit||0),0).toFixed(2);const avgProfit=(totalProfit/total).toFixed(2);const profits=orders.map(o=>o.profit||0);const best=Math.max(...profits).toFixed(2);const worst=Math.min(...profits).toFixed(2);const longs=orders.filter(o=>o.type==='buy'||o.type==='BUY');const shorts=orders.filter(o=>o.type==='sell'||o.type==='SELL');const longWin=longs.length?((longs.filter(o=>o.profit>0).length/longs.length)*100).toFixed(1)+'%':'—';const shortWin=shorts.length?((shorts.filter(o=>o.profit>0).length/shorts.length)*100).toFixed(1)+'%':'—';document.getElementById('statTrades').textContent=total;document.getElementById('statWinRate').textContent=winRate;document.getElementById('statTotalProfit').textContent=totalProfit;document.getElementById('statAvgProfit').textContent=avgProfit;document.getElementById('statBestTrade').textContent=best;document.getElementById('statWorstTrade').textContent=worst;document.getElementById('statLongWin').textContent=longWin;document.getElementById('statShortWin').textContent=shortWin;}
function sortTable(tableId,col){const table=document.getElementById(tableId);const tbody=table.querySelector('tbody');const rows=Array.from(tbody.querySelectorAll('tr'));const asc=table.dataset.sortCol==col&&table.dataset.sortDir==='asc';table.dataset.sortCol=col;table.dataset.sortDir=asc?'desc':'asc';rows.sort((a,b)=>{const aVal=a.cells[col]?.textContent.trim()||'';const bVal=b.cells[col]?.textContent.trim()||'';const aNum=parseFloat(aVal);const bNum=parseFloat(bVal);if(!isNaN(aNum)&&!isNaN(bNum))return asc?bNum-aNum:aNum-bNum;return asc?bVal.localeCompare(aVal):aVal.localeCompare(bVal);});rows.forEach(r=>tbody.appendChild(r));}
function calcPipValue(){const pair=document.getElementById('pipPair').value;const lot=parseFloat(document.getElementById('pipLot').value)||1;const pipMap={EURUSD:10,GBPUSD:10,AUDUSD:10,USDCAD:7.7,USDJPY:9.1,XAUUSD:1};const base=pipMap[pair]||10;const val=(base*lot).toFixed(2);document.getElementById('pipResult').textContent=`Pip Value ≈ USD ${val} / pip`;}
function calcPositionSize(){const acc=parseFloat(document.getElementById('psAccSize').value)||10000;const risk=parseFloat(document.getElementById('psRisk').value)||1;const sl=parseFloat(document.getElementById('psSL').value)||20;const pipVal=parseFloat(document.getElementById('psPipVal').value)||10;const riskAmt=(acc*risk/100);const lots=(riskAmt/(sl*pipVal)).toFixed(2);document.getElementById('psResult').textContent=`Position Size ≈ ${lots} Lots  (Risk: $${riskAmt.toFixed(2)})`;}
function calcRR(){const entry=parseFloat(document.getElementById('rrEntry').value);const sl=parseFloat(document.getElementById('rrSL').value);const tp=parseFloat(document.getElementById('rrTP').value);if(isNaN(entry)||isNaN(sl)||isNaN(tp)){document.getElementById('rrResult').textContent='Invalid input';return;}const risk=Math.abs(entry-sl);const reward=Math.abs(tp-entry);const rr=(reward/risk).toFixed(2);document.getElementById('rrResult').textContent=`R:R = 1 : ${rr}  |  Risk ${(risk*10000).toFixed(1)} pips  |  Reward ${(reward*10000).toFixed(1)} pips`;}
function calcMargin(){const lot=parseFloat(document.getElementById('mgLot').value)||1;const lev=parseFloat(document.getElementById('mgLeverage').value)||100;const price=parseFloat(document.getElementById('mgPrice').value)||1.1;const margin=(lot*100000*price/lev).toFixed(2);document.getElementById('mgResult').textContent=`Required Margin ≈ USD ${margin}`;}
function calcPL(){const lot=parseFloat(document.getElementById('plLot').value)||1;const open=parseFloat(document.getElementById('plOpen').value);const close=parseFloat(document.getElementById('plClose').value);const dir=document.getElementById('plDir').value;if(isNaN(open)||isNaN(close)){document.getElementById('plResult').textContent='Invalid input';return;}const diff=dir==='buy'?close-open:open-close;const pl=(diff*lot*100000).toFixed(2);const cls=parseFloat(pl)>=0?'pos':'neg';document.getElementById('plResult').innerHTML=`<span class="${cls}">P/L ≈ USD ${pl}</span>`;}
function calcSwap(){const lot=parseFloat(document.getElementById('swLot').value)||1;const rate=parseFloat(document.getElementById('swRate').value)||-2.5;const days=parseFloat(document.getElementById('swDays').value)||1;const swap=(lot*rate*days).toFixed(2);const cls=parseFloat(swap)>=0?'pos':'neg';document.getElementById('swResult').innerHTML=`<span class="${cls}">Swap ≈ USD ${swap}</span>`;}
document.addEventListener('DOMContentLoaded',()=>{document.documentElement.className=currentTheme;const ts=document.getElementById('themeSelect');if(ts)ts.value=currentTheme;const ls=document.getElementById('langSelect');if(ls)ls.value=currentLang;navigate('home');});

